### ISSUE TITLE
writing images from outside to canvas... ctx.drawImage( )

### ISSUE THREAD

**Issue by mango314** [evancz/elm-graphics#9]
Here is an example I would like to work in Elm

```
    var width  = 960;
    var height = 500;

    var canvas = document.getElementById('vincent');
    var ctx = canvas.getContext("2d");
    canvas.width  = width;
    canvas.height = height;

    var image = new Image();
    image.src= "starry-night.jpg";
    image.onload = function () { ctx.drawImage(image, 0, 0); }
```

unfortunately I can't find anything in the [`Graphics`](http://package.elm-lang.org/packages/evancz/elm-graphics/1.0.0/) library.  

Possibly since "starry-night.jpg" is an image from the outside world...  such a function could have type `Form -> Maybe Form`  

I wrote a subscription if you want to see it... I might try writing a NativeJS library for that one thing...

**Comment by jvoigtlaender** [comment]
Why can't you use one of the functions "image" etc. from http://package.elm-lang.org/packages/evancz/elm-graphics/1.0.0/Element#image to achieve what you want?

**Comment by mango314** [comment]
@jvoigtlaender perfect. moving down the chain here is `context.getImageData(0, 0, width, height);` 

even my first question, not to many people were familiar with it.  Perhaps you can add a code example in the docs? `image 960 500 "starry-night.jpg"`

http://stackoverflow.com/questions/37548314/how-to-access-image-data-in-elm

**Comment by jvoigtlaender** [comment]
The `croppedImage` and `tiledImage` functions do have code examples in the docs. Certainly you can add corresponding examples for `image` and `fittedImage` in a pull request.

The question about getting image dimension data is separate, and should be opened as a separate issue, I think.

And this issue here can now be closed?

**Comment by mango314** [comment]
I will close this issue.
